apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  namespace: haruotsu
  labels:
    app: flask-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask-app
          image: 905418468932.dkr.ecr.us-east-1.amazonaws.com/haruotsu-flask-images:latest
          ports:
            - containerPort: 5000
      imagePullSecrets:
        - name: ecr-secret
