apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flask-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/hrt-ykym/productRecommendation.git"
    targetRevision: HEAD
    path: "kubernetes/flask"
    kustomize:
  destination:
    server: "https://kubernetes.default.svc"
    namespace: haruotsu
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
