services:
  web:
    # network_mode: "host" # これを書かないと、コンテナごとにnamespaceをつくるようになる
    build:
      context: ./productRecommendation-system
    command: /bin/bash -c "rm -rf /app/tmp/pids/server.pid && bin/rails server -b 0.0.0.0"
    volumes:
      - ./productRecommendation-system:/app
    ports:
      - "3000:3000"

  recommendationengine:
    # network_mode: "host"
    build:
      context: ./recommendationEngine
    volumes:
      - ./recommendationEngine:/app
    ports:
      - "5000:5000"

volumes:
  pgdata: