apiVersion: apps/v1
kind: Deployment
metadata:
  name: rails-app
  namespace: haruotsu
  labels:
    app: rails-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rails-app
  template:
    metadata:
      labels:
        app: rails-app
    spec:
      containers:
        - name: rails-app
          image: 905418468932.dkr.ecr.us-east-1.amazonaws.com/haruotsu-rails-images:latest
          ports:
            - containerPort: 3000
          env:
            - name: FLASK_SERVICE_URL
              value: "http://flask-service.haruotsu.svc.cluster.local:80"
            - name: ALLOWED_HOSTS
              value: "rails-service.haruotsu.svc.cluster.local,web,localhost"
      imagePullSecrets:
        - name: ecr-secret
