apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rails-app
  namespace: haruotsu
spec:
  project: default
  source:
    repoURL: "https://github.com/hrt-ykym/productRecommendation.git"
    targetRevision: HEAD
    path: "kubernetes/rails"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: rails-namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
