name: CI

on: [push, pull_request]

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.3

      - name: Install system dependencies
        run: sudo apt-get update

      - name: Install Ruby dependencies
        run: |
          cd productRecommendation-system
          gem install bundler -v 2.5.6
          bundle install

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "14"

      - name: Install Node.js dependencies
        run: |
          cd productRecommendation-system
          npm install

      - name: Prepare database
        run: |
          cd productRecommendation-system
          bin/rails db:create db:migrate

      - name: Run tests
        run: |
          cd productRecommendation-system
          bundle exec rspec
